language: node_js

nodejs: '12'

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - npm install -g vsce

install:
  - npm install

script:
  - npm run webpack

deploy:
  - provider: script
    script: vsce publish -p $VSCE_TOKEN
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v\d+\.\d+\.\d+$