language: node_js

nodejs: '12'

os:
- linux
- macos
- windows

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
- npm install -g vsce

install:
- npm install

script:
- npm run webpack