language: node_js

nodejs: '12'

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

branches:
  only:
    - dev

before_install:
  - npm install -g vsce

install:
  - npm install

script:
  - npm run webpack
