image: node:16

pipelines:
  custom:
    Build:
      - step:
          name: build
          caches:
            - node
          script:
            - npm install -g @vscode/vsce
            - npm install
            - vsce package
          artifacts:
            - '*.vsix'
      - step:
          name: upload nodemcu-tools.vsix to download location
          script:
            - pipe: atlassian/bitbucket-upload-file:0.3.4
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: '*.vsix'
